language: python
python:
  - "3.8"
dist: xenial
sudo: required
addons:
  apt:
    sources:
      - sourceline: 'ppa:deadsnakes/ppa'
      - sourceline: 'ppa:travis-ci/sqlite3'
    packages:
      - sqlite3
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sqlite3 libsqlite3-dev
  - sqlite3 --version
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py test
