language: python
python:
  - "3.8"
dist: xenial
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y wget
  - wget https://www.sqlite.org/2023/sqlite-autoconf-3420000.tar.gz
  - tar xzf sqlite-autoconf-3420000.tar.gz
  - cd sqlite-autoconf-3420000
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
  - sqlite3 --version
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py test

