language: python
python:
  - "3.8"
dist: xenial
sudo: required
before_install:
  - wget https://www.sqlite.org/2023/sqlite-autoconf-3420000.tar.gz
  - tar xzf sqlite-autoconf-3420000.tar.gz
  - cd sqlite-autoconf-3420000
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  - cd ..
  - export PATH="/usr/local/bin:$PATH"
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  - echo "SQLite version after update:"
  - sqlite3 --version  # Verify the new SQLite version
install:
  - pip install -r requirements.txt
script:
  - which sqlite3  # Check which sqlite3 is being used
  - ls -l /usr/local/bin/sqlite3  # Verify the installation path
  - python3 manage.py migrate
  - python3 manage.py test
